package HTMLToFunction;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Convert {

    private static String escapeLine(String line) {
        // Escape backslashes and double quotes; drop '\r' if present
        StringBuilder sb = new StringBuilder(line.length() * 2 + 16);
        for (int i = 0; i < line.length(); i++) {
            char c = line.charAt(i);
            if (c == '\r') continue;              // normalize CRLF -> LF
            if (c == '\\' || c == '\"') {
                sb.append('\\').append(c);
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }

    public static void main(String[] args) {
        if (args.length < 1 || args.length > 2) {
            System.err.println("Usage: java Convert <input.html> [output.txt]");
            System.exit(1);
        }

        String inPath = args[0];
        String outPath = (args.length == 2) ? args[1] : "./createHTMLFiles/createHTML.txt";

        // Get timestamp
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String timestamp = LocalDateTime.now().format(fmt);

        try (BufferedReader br = Files.newBufferedReader(Paths.get(inPath), StandardCharsets.UTF_8);
             BufferedWriter bw = Files.newBufferedWriter(Paths.get(outPath), StandardCharsets.UTF_8)) {

            // File header comment with date
            bw.write("// Auto-generated by Convert on " + timestamp + "\n\n");

            // Header
            bw.write("String createHTML() {\n");
            bw.write("  String str = \"\";\n");

            // Body: line-by-line to keep memory small and preserve structure
            String line;
            while ((line = br.readLine()) != null) {
                String escaped = escapeLine(line);
                bw.write("  str += \"");
                bw.write(escaped);
                bw.write("\\n\";\n");
            }

            // Footer
            bw.write("  return str;\n");
            bw.write("}\n");

            bw.flush();
            System.out.println("Wrote Arduino String function to: " + outPath);

        } catch (FileNotFoundException e) {
            System.err.println("Input file not found: " + inPath);
            System.exit(2);
        } catch (IOException e) {
            System.err.println("I/O error: " + e.getMessage());
            System.exit(3);
        }
    }
}
